### ISSUE TITLE
Error 500: java.lang.IllegalArgumentException: Illegal cookie attribute with IBM JDK

### ISSUE THREAD

**Issue by long800110** [mitre/HTTP-Proxy-Servlet#172]
There is an Error 500: java.lang.IllegalArgumentException: Illegal cookie attribute issue thrown with WebSphere 7 (IBM JDK 6

SRVE0293E: [Servlet Error]-[testProxy]: java.lang.IllegalArgumentException: Illegal cookie attribute
	at java.net.HttpCookie.assignAttribute(HttpCookie.java:1013)
	at java.net.HttpCookie.parseInternal(HttpCookie.java:921)
	at java.net.HttpCookie.parse(HttpCookie.java:182)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.copyProxyCookie(ProxyServlet.java:537)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.copyResponseHeader(ProxyServlet.java:515)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.copyResponseHeaders(ProxyServlet.java:500)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.service(ProxyServlet.java:341)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:831))

**Comment by dsmiley** [comment]
Sorry, I don't have time to debug this.  I suspect there is some cookie being sent that is out-of-spec, and java.net.HttpCookie is being strict.
