### ISSUE TITLE
ClassNotFoundException org.apache.http.conn.ClientConnectionManager

### ISSUE THREAD

**Issue by cd0304** [mitre/HTTP-Proxy-Servlet#50]
when i use tomcat 6 run the serverlet, it throw this error

why?

Servlet /gdds threw load() exception
java.lang.ClassNotFoundException: org.apache.http.conn.ClientConnectionManager
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1516)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1361)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
	at java.lang.Class.getConstructor0(Class.java:2699)
	at java.lang.Class.newInstance0(Class.java:326)
	at java.lang.Class.newInstance(Class.java:308)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1116)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:993)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4187)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4496)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1041)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:964)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
	at org.apache.catalina.core.StandardService.start(StandardService.java:519)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)

my web.xml:
<servlet>
    <servlet-name>solr</servlet-name>
    <servlet-class>org.mitre.dsmiley.httpproxy.ProxyServlet</servlet-class>
    <init-param>
      <param-name>targetUri</param-name>
      <param-value>http://solrserver:8983/solr</param-value>
    </init-param>
    <init-param>
      <param-name>log</param-name>
      <param-value>true</param-value>
    </init-param>
     <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
  <servlet-name>solr</servlet-name>
  <url-pattern>/solr/*</url-pattern>
</servlet-mapping>

**Comment by dsmiley** [comment]
This servlet requires Apache Commons HttpClient to work.

**Comment by cd0304** [comment]
i want to developer a proxy servlet ,i use tomcat to run a server,so how i can do it
 in my project ,how to import the Apache HttpClient.
A complete web project is how to do?

**Comment by dsmiley** [comment]
Minimally, you need this servlet (say in a '.jar' available from Maven, or you could compile it), and it's dependencies, which can be downloaded here:
https://hc.apache.org/downloads.cgi
And of course you need a web.xml configured but it seems you have that.

**Comment by cd0304** [comment]
i have copy HttpClient jar to my web lib  directory, and this can work very well ,most of web can be proxy this it.

but some web  site,it proxy will throw error, i do not know why

in my web.xml:
targetUri :   http://14.29.1.32:8083
url-pattern :  /*



this web site http://14.29.1.32:8083 ,i can open it in my browser
but with this proxy ,it throw error bellow:


015-3-22 22:03:57 org.apache.catalina.core.AprLifecycleListener init
信息: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: D:\softwave\myeclipse\Common\binary\com.sun.java.jdk.win32.x86_64_1.6.0.013\bin;D:\softwave\Tomcat 6.0\bin
2015-3-22 22:03:58 org.apache.coyote.http11.Http11Protocol init
信息: Initializing Coyote HTTP/1.1 on http-8080
2015-3-22 22:03:58 org.apache.catalina.startup.Catalina load
信息: Initialization processed in 468 ms
2015-3-22 22:03:58 org.apache.catalina.core.StandardService start
信息: Starting service Catalina
2015-3-22 22:03:58 org.apache.catalina.core.StandardEngine start
信息: Starting Servlet Engine: Apache Tomcat/6.0.26
2015-3-22 22:03:58 org.apache.catalina.startup.HostConfig deployDescriptor
信息: Deploying configuration descriptor manager.xml
2015-3-22 22:03:58 org.apache.catalina.startup.HostConfig deployDirectory
信息: Deploying web application directory docs
2015-3-22 22:03:58 org.apache.catalina.startup.HostConfig deployDirectory
信息: Deploying web application directory gdds
2015-3-22 22:03:58 org.apache.catalina.startup.HostConfig deployDirectory
信息: Deploying web application directory ROOT
2015-3-22 22:03:58 org.apache.coyote.http11.Http11Protocol start
信息: Starting Coyote HTTP/1.1 on http-8080
2015-3-22 22:03:58 org.apache.jk.common.ChannelSocket init
信息: JK: ajp13 listening on /0.0.0.0:8009
2015-3-22 22:03:58 org.apache.jk.server.JkMain start
信息: Jk running ID=0 time=0/23  config=null
2015-3-22 22:03:58 org.apache.catalina.startup.Catalina start
信息: Server startup in 750 ms
2015-3-22 22:04:14 org.apache.catalina.core.ApplicationContext log
信息: gdds: proxy GET uri: /gdds/assets/index.html -- http://14.29.1.32:8083/assets/index.html
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.PoolingClientConnectionManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2015-3-22 22:04:15 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet gdds threw exception
java.lang.IllegalArgumentException: Illegal cookie attribute
	at java.net.HttpCookie.assignAttribute(HttpCookie.java:1002)
	at java.net.HttpCookie.parseInternal(HttpCookie.java:910)
	at java.net.HttpCookie.parse(HttpCookie.java:171)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.copyProxyCookie(ProxyServlet.java:443)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.copyResponseHeaders(ProxyServlet.java:431)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.service(ProxyServlet.java:283)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:852)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:619)

**Comment by dsmiley** [comment]
The error in their with the reference to Log4j explains further what you
should do.  Essentially you need to add a log4j jar as well.

~ David Smiley
Freelance Apache Lucene/Solr Search Consultant/Developer
http://www.linkedin.com/in/davidwsmiley

**Comment by cd0304** [comment]
my lib have this jar:
log4j-1.2.16.jar
jstl-1.2.jar
httpcore-4.3.2.jar
httpclient-4.3.4.jar
commons-logging-1.1.3.jar
commons-codec-1.6.jar

**Comment by dsmiley** [comment]
oh nevermind; you’re good here.  The log4j *warning* was just about log4j
not being configured.

The error says the cookie is illegal.  You should debug (i.e. using a
debugger) and try to see what’s going on there to know more.  If you tell
me exactly what the Cookie headers sent were (and what sent them; e.g. a
browser) then maybe I can help.

~ David Smiley
Freelance Apache Lucene/Solr Search Consultant/Developer
http://www.linkedin.com/in/davidwsmiley

**Comment by cd0304** [comment]
ok,Thank you very much for your answer
i try to debug it 
Thank you !!

**Comment by cd0304** [comment]
Have find the problem reason:
head : JSESSIONID=593D1F7AA0AEB81B6081F1E394ADFEFE; Path=/education/; HttpOnly
so , the code :  cookies = HttpCookie.parse( header.getValue());

this will throw error in jdk 1.6 ,but with jdk1.8 ,it is ok


i find this is broblem because the HttpOnly , when i remove HttpOnly, everything is ok.

my fix code :       in ProxyServlet.java ->copyProxyCookie  line 448

String str = header.getValue();
StringBuilder buf = new StringBuilder();
String[] str =  str.split(";");
for(String tem :str) {
    if(!tem.equals("HttpOnly")) {
    buf.append(tem);
buf.append(";");
    }
}
List<HttpCookie> cookies = HttpCookie.parse(buf.toSting());


have There's a better way?

**Comment by dsmiley** [comment]
Interesting.  Jdk 1.6 is pretty old... I think I'm inclined to simply say that the proxy supports Java 1.7 and forward now.  I know the fix is simple for you to apply locally, which you could do in a subclass if you want to.

**Comment by cd0304** [comment]
because my runtime is java 1.6 , and i can not change it.    can i  be in 1.7 compile, then run on the jre 1.6?

**Comment by dsmiley** [comment]
No.  Alternatively, perhaps you can suggest an approach to use HttpComponent's classes instead of java.net platform ones to parse the cookie.  If you get it working, please provide in a pull request.
