### ISSUE TITLE
HttpResponse not closed

### ISSUE THREAD

**Issue by hrbapna** [mitre/HTTP-Proxy-Servlet#62]
The method consumeQuietly just closes the HttpEntity and not the HttpResponse.

I am using the HTTP-Proxy-Servlet to proxy requests from one tomee to another tomee. I have observed an issue on tomcat: All default HTTP threads of tomcat are getting exhausted as observedJVM jstack thread dump and it is not able to accept any further requests.
I think that ProxyServlet is not closing the connection cleanly as suggested in the https://hc.apache.org/httpcomponents-client-ga/quickstart.html

finally {
    if(response != null) {
      // This call is necessary to consume the entire content of the response (entity) so that 
the manager can release the connection back to the pool.
       EntityUtils.consume(response.getEntity());
       response.close();
     }
}

"http-bio-8080-exec-944" daemon prio=10 tid=0x00007f876c202800 nid=0x5de6 waiting on condition [0x00007f874dd5b000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000074385c758> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:133)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:282)
	at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:177)
	at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:170)
	at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:102)
	at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:208)
	at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:422)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.mitre.dsmiley.httpproxy.ProxyServlet.service(ProxyServlet.java:227)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:45)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at com.ca.emm.essfilter.AuthzTomcatValve.invoke(AuthzTomcatValve.java:154)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	- locked <0x0000000743845020> (a org.apache.tomcat.util.net.SocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)

**Comment by hrbapna** [comment]
If u agree with the reasoning that I can create a pull request.

**Comment by dsmiley** [comment]
Pull request welcome :-)  Just looking at the code... I don't see a close() method on HttpResponse.java but then realized it's in CloseableHttpResponse.  So remember to check instanceof Closeable.  I don't want the code to require v4.3.

**Comment by hrbapna** [comment]
But the project already lists http client 4.5 as dependency.


    <httpclient.version>4.5</httpclient.version>

**Comment by dsmiley** [comment]
In Maven you have to list a version; it needn't be the least supported version.  I chose to list the most recent version to encourage people to use new software.  In the pom.xml you should see comments about supporting back to v4.1.  In any case, the feature here doesn't require knowledge of any new HttpClient APIs; just check instanceof Closeable.

**Comment by hrbapna** [comment]
got it. I am unable to push to a remote branch as a precursor to generating a pull request.
I think i don't have permission to push to mitre so can u tell me how to generate a pull request.

remote: Permission to mitre/HTTP-Proxy-Servlet.git denied to hrbapna.
fatal: unable to access 'https://github.com/mitre/HTTP-Proxy-Servlet.git/': The requested URL returned error: 403

**Comment by dsmiley** [comment]
You should fork the repo using Github's UI and commit there.
On Tue, Aug 11, 2015 at 3:39 PM hrbapna <notifications@github.com> wrote:

> got it. I am unable to push to a remote branch as a precursor to
> generating a pull request.
> I think i don't have permission to push to mitre so can u tell me how to
> generate a pull request.
>
> remote: Permission to mitre/HTTP-Proxy-Servlet.git denied to hrbapna.
> fatal: unable to access 'https://github.com/mitre/HTTP-Proxy-Servlet.git/':
> The requested URL returned error: 403
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitre/HTTP-Proxy-Servlet/issues/62#issuecomment-130036990>
> .
>
-- 
Lucene/Solr Search Committer, Consultant, Developer, Author, Speaker
LinkedIn: http://linkedin.com/in/davidwsmiley | Book:
http://www.solrenterprisesearchserver.com
